### ISSUE TITLE
Labels do not work when using Filter view instead of opening jira ticket.

### ISSUE THREAD

**Issue by mnmshareme** [nemozny/chrome-plugin-jira-labels#1]
Modifying updateTicket as below should make label assignment work in filtered view. 

function updateTicket(payload) {
  var jira = document.getElementsByName('ajs-issue-key')[0];

**// data-issue-key should be used when editing with in a filters window**

  if(typeof(jira) == 'undefined') {
    var jira = document.getElementById("s-helper-panel-content").getAttribute('data-issue-key')
  } else {
    var jira=jira.getAttribute('content')
  }
  let url = document.getElementsByName('ajs-base-url')[0].getAttribute('content')
.....

**Comment by nemozny** [comment]
@mnmshareme can you please explain to me what is a Filter view? Ideally with a screenshot?
Because I am trying to figure it out since you have posted this.

**Comment by mnmshareme** [comment]
@nemozny something like this view 
![search_detailview](https://user-images.githubusercontent.com/109177056/179799707-90064102-bfc1-4149-ab50-aa09fdae1da0.png)

**Comment by nemozny** [comment]
Oh, do you mean the right side?
Edit: I was worried you wanted to bulk add labels to multiple tickets. The right side is a good idea.

**Comment by mnmshareme** [comment]
Yes, I meant right side. Using data-issue-key as I placed in code snippet above should allow adding label to a single issue.

**Comment by nemozny** [comment]
Thanks, verified and updated!
